import { v4 as uuidv4 } from "uuid";
function chillHop() {
  return [
    {
      name: "unnamed",
      cover: require("./images/sick1logo.jpg"),
      artist: "Eric Nickus",
      audio: require("./music/unnamed.mp3"),
      color: ["#205950", "#2ab3bf"],
      id: uuidv4(),
      active: true,
    },
    {
      name: "you could have got a job",
      cover: require("./images/sick1logo.jpg"),
      artist: "Eric Nickus",
      audio: require ("./music/youcouldhavegottajob4.mp3"),
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    
    {
      name: "onemore",
      cover: require("./images/sick1logo.jpg"),
      artist: "Eric Nickus",
      audio: require("./music/onemore.mp3"),
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "x2ciool",
      cover: require("./images/sick1logo.jpg"),
      artist: "Eric Nickus",
      audio: require ("./music/x2ciool.mp3"),
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "jacks song",
      cover: require("./images/sick1logo.jpg"),
      artist: "Eric Nickus",
      audio: require("./music/jackssong.mp3"),
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "project 44",
      cover: require("./images/sick1logo.jpg"),
      artist: "Eric Nickus",
      audio: require ("./music/Project 44.mp3"),
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "friday morning",
      cover: require("./images/sick1logo.jpg"),
      artist: "Eric Nickus",
      audio: require ("./music/Fridaymorning.mp3"),
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "sick8",
      cover: require("./images/sick1logo.jpg"),
      artist: "Eric Nickus",
      audio: require("./music/sick8.mp3"),
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "xxx",
      cover: require("./images/sick1logo.jpg"),
      artist: "Eric Nickus",
      audio: require ("./music/xxx.mp3"),
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "COOL52REMIX",
      cover: require("./images/sick1logo.jpg"),
      artist: "Eric Nickus",
      audio: require("./music/COOL52REMIX.mp3"),
      color: ["#205950", "#2ab3bf"],
      id: uuidv4(),
      active: true,
    },
   
    {
      name: "all me",
      cover: require("./images/sick1logo.jpg"),
      artist: "Eric Nickus",
      audio: require("./music/allme1.mp3"),
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },

    {
      name: "indiavocals",
      cover: require("./images/sick2.jpg"),
      artist: "Eric Nickus",
      audio: require("./music/indiavocals.mp3"),
      color: ["#205950", "#2ab3bf"],
      id: uuidv4(),
      active: true,
    },
    {
      name: "bassmadness",
      cover: require("./images/sick2.jpg"),
      artist: "Eric Nickus",
      audio: require ("./music/bassmadness.mp3"),
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "bbest5.1",
      cover: require("./images/sick2.jpg"),
      artist: "Eric Nickus",
      audio: require ("./music/bbest5.1.mp3"),
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    
    {
      name: "1-newstuff",
      cover: require("./images/sick2.jpg"),
      artist: "Eric Nickus",
      audio: require ("./music/1-newstuff.mp3"),
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "do you in the * * * * ",
      cover: require("./images/sick2.jpg"),
      artist: "Eric Nickus",
      audio: require("./music/doyouinthebutt2.mp3"),
      color: ["#205950", "#2ab3bf"],
      id: uuidv4(),
      active: true,
    },
   
    {
      name: "funkloop1",
      cover: require("./images/sick2.jpg"),
      artist: "Eric Nickus",
      audio: require("./music/funkloop1.mp3"),
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "greatestelectonicv",
      cover: require("./images/sick2.jpg"),
      artist: "Eric Nickus",
      audio: require ("./music/greatestelectronicv.mp3"),
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    
    {
      name: "intenseone",
      cover: require("./images/sick2.jpg"),
      artist: "Eric Nickus",
      audio: require ("./music/intenseone.mp3"),
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
   
    {
      name: "new bs",
      cover: require("./images/sick2.jpg"),
      artist: "Eric Nickus",
      audio: require ("./music/newbuklshit3.mp3"),
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "newelectronic3",
      cover: require("./images/sick2.jpg"),
      artist: "Eric Nickus",
      audio: require ("./music/newelectronic3.mp3"),
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    
   
    //ADD MORE HERE
  ];
}

export default chillHop;
